import { GoogleGenAI } from "@google/genai";

const ai = new GoogleGenAI({ apiKey: process.env.API_KEY });

export const explainHypothesis = async (compound: string, protein: string): Promise<string> => {
  try {
    const model = "gemini-2.5-flash";
    const prompt = `
      Act as a senior computational biologist and pharmacologist.
      I have a predicted interaction between the compound "${compound}" and the target protein "${protein}" generated by a Graph Neural Network for drug repurposing.
      
      Please provide a concise, scientific hypothesis (max 3 sentences) explaining why this interaction might be biologically plausible or relevant for therapeutic use. 
      Focus on mechanism of action, pathway involvement, or structural similarity if known.
      If the link is highly speculative, mention that it warrants wet-lab validation.
    `;

    const response = await ai.models.generateContent({
      model: model,
      contents: prompt,
    });

    return response.text || "No explanation generated.";
  } catch (error) {
    console.error("Gemini API Error:", error);
    return "Unable to retrieve analysis at this time. Please check API configuration.";
  }
};

export const generateSynthesizedData = async (): Promise<string> => {
    // Helper to generate more mock data if needed, or just simulate "live" data fetch
    // Not strictly used in the main flow but good to have for expansion
    return "Data synthesized.";
}
